global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product-selection-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-selection-service:8080']
        labels:
          service: 'product-selection-service'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8080']
        labels:
          service: 'payment-service'

  - job_name: 'product-delivery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-delivery-service:8080']
        labels:
          service: 'product-delivery-service'

  - job_name: 'courier-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['courier-service:8080']
        labels:
          service: 'courier-service'

  - job_name: 'axon-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['axon-server:8024']
        labels:
          service: 'axon-server'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
