spring:
  application:
    name: product-delivery-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://postgres-product-delivery:5432/db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    jackson:
      property-naming-strategy: SNAKE_CASE

server:
  port: 8080

axon:
  axonserver:
    servers: axon-server:8124

management:
  metrics:
    enable:
      process.cpu: false
      system: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Product Delivery Service API
    description: API for managing product delivery in the delivery bounded context
    version: 1.0.0

logging:
  loki:
    url: http://loki:3100
