spring:
  application:
    name: product-delivery-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://0.0.0.0:5438/db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    jackson:
      property-naming-strategy: SNAKE_CASE

server:
  port: 8082

axon:
  axonserver:
    servers: 0.0.0.0:8124

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Product Delivery Service API
    description: API for managing product delivery in delivery bounded context
    version: 1.0.0

logging:
  loki:
    url: http://localhost:3100
