apiVersion: 1

datasources:
    - name: DS_PROMETHEUS
      type: prometheus
      uid: prometheus_main_uid
      url: http://prometheus:9090
      isDefault: true
      editable: false
      access: proxy
    - name: DS_LOKI
      type: loki
      uid: loki_main_uid
      url: http://loki:3100
      isDefault: false
      access: proxy

