spring:
  application:
    name: courses-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    jackson:
      property-naming-strategy: SNAKE_CASE

server:
  port: 8081

axon:
  axonserver:
    servers: 0.0.0.0:8124

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

logging:
  loki:
    url: http://localhost:3100